services:
    api:
        # build: 
            # context: ./api
            # dockerfile: Dockerfile.env
        build: ./api
        container_name: test_api
        ports:
            - "3500:3500"
        volumes: 
            - ./api:/api